services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - TITANIC_SERVICE_URL=http://titanic-service:9001
      - CRIME_SERVICE_URL=http://crime-service:9002
      - MATZIP_SERVICE_URL=http://matzip-service:9003
    networks:
      - ai-network

  titanic-service:
    build:
      context: ./titanic-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - ai-network

  crime-service:
    build:
      context: ./crime-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - ai-network

  matzip-service:
    build:
      context: ./matzip-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
  
